/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiRecordingIdVideoRouteImport } from './routes/api.recording.$id.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordingIdVideoRoute = ApiRecordingIdVideoRouteImport.update({
  id: '/api/recording/$id/video',
  path: '/api/recording/$id/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/share/$id': typeof ShareIdRoute
  '/api/recording/$id/video': typeof ApiRecordingIdVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/share/$id': typeof ShareIdRoute
  '/api/recording/$id/video': typeof ApiRecordingIdVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/share/$id': typeof ShareIdRoute
  '/api/recording/$id/video': typeof ApiRecordingIdVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/upload' | '/share/$id' | '/api/recording/$id/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/upload' | '/share/$id' | '/api/recording/$id/video'
  id:
    | '__root__'
    | '/'
    | '/api/upload'
    | '/share/$id'
    | '/api/recording/$id/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiRecordingIdVideoRoute: typeof ApiRecordingIdVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recording/$id/video': {
      id: '/api/recording/$id/video'
      path: '/api/recording/$id/video'
      fullPath: '/api/recording/$id/video'
      preLoaderRoute: typeof ApiRecordingIdVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadRoute: ApiUploadRoute,
  ShareIdRoute: ShareIdRoute,
  ApiRecordingIdVideoRoute: ApiRecordingIdVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
